export const GET_ALLSERVICES_REQUEST = "GET_ALLSERVICES_REQUEST";
export const GET_ALLSERVICES_SUCCESS = "GET_ALLSERVICES_SUCCESS";
export const GET_ALLSERVICES_FAILED = "GET_ALLSERVICES_FAILED";

export const GET_ALLSERVICES_TIERS_REQUEST = "GET_ALLSERVICES_TIERS_REQUEST";
export const GET_ALLSERVICES_TIERS_SUCCESS = "GET_ALLSERVICES_TIERS_SUCCESS";
export const GET_ALLSERVICES_TIERS_FAILED = "GET_ALLSERVICES_TIERS_FAILED";

export const POST_USER_SERVICES_REQUEST = "POST_USER_SERVICES_REQUEST";
export const POST_USER_SERVICES_SUCCESS = "POST_USER_SERVICES_SUCCESS";
export const POST_USER_SERVICES_FAILED = "POST_USER_SERVICES_FAILED";
